disabled_rules:
 - trailing_whitespace
 - type_name
 - notification_center_detachment
 - cyclomatic_complexity
 - function_body_length
 - switch_case_alignment
 - multiple_closures_with_trailing_closure
 - closure_end_indentation

opt_in_rules:
 - closure_end_indentation
 - closure_spacing
 - empty_count
 - fatal_error_message
 - first_where
 - force_unwrapping
 - implicitly_unwrapped_optional

type_body_length:
  warning: 400
  error: 500

file_length:
  warning: 650
  error: 1000

large_tuple:
  warning: 3
  error: 4

function_parameter_count:
  warning: 6
  error: 8

line_length:
  warning: 200
  error: 220
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

identifier_name:
  min_length:
    warning: 0
    error: 2
  max_length: # only min_length
    error: 30 # only error
  excluded: # excluded via string array
    - i

#custom rules
custom_rules:
  no_prints: # rule identifier
    included: ".*\\.swift" # regex that defines paths to include during linting. optional.
    name: "No prints in commits" # rule name. optional.
    regex: "([p,P]rint)" # matching pattern
    capture_group: 0 # number of regex capture group to highlight the rule violation at. optional.
    message: "Please remove before commit" # violation message. optional.

included:
  - APOD

excluded:
  - Packages
